export interface Dua {
  id: string;
  category: "subah" | "shaam" | "namaz" | "safar" | "khana" | "sone";
  arabic: string;
  romanUrdu: string;
  urdu: string;
  telugu: string;
  source?: string;
  isCustom?: boolean;
}

export const DUA_DATA: Dua[] = [
  // ── SUBAH (Morning) ──
  {
    id: "s1",
    category: "subah",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا",
    romanUrdu: "Allahumma bika asbahna wa bika amsayna",
    urdu: "اے اللہ! تیری توفیق سے ہم نے صبح کی اور تیری توفیق سے شام کریں گے",
    telugu: "ఓ అల్లాహ్! నీ సహాయంతో మేము ఉదయించాం, నీ సహాయంతో సాయంత్రమవుతాం",
    source: "Abu Dawud",
  },
  {
    id: "s2",
    category: "subah",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ",
    romanUrdu: "Asbahna wa asbahal mulku lillah",
    urdu: "ہم نے صبح کی اور ساری بادشاہت اللہ کے لیے ہے",
    telugu: "మేము ఉదయించాం, రాజ్యం అల్లాహ్‌కే చెందుతుంది",
  },
  {
    id: "s3",
    category: "subah",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    romanUrdu: "La ilaha illallahu wahdahu la sharika lah",
    urdu: "اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں",
    telugu: "అల్లాహ్ తప్ప ఆరాధ్యుడు లేడు, ఆయన ఒంటరిగా ఉన్నాడు, ఆయనకు భాగస్వామి లేడు",
    source: "Bukhari",
  },
  {
    id: "s4",
    category: "subah",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ",
    romanUrdu: "Bismillahil ladhi la yadurru ma'asmihi shay'un",
    urdu: "اللہ کے نام سے جس کے نام کے ساتھ کوئی چیز نقصان نہیں دیتی",
    telugu: "అల్లాహ్ పేరుతో — దేనీ నష్టం కలగదు ఆయన పేరుతో",
    source: "Tirmidhi",
  },
  {
    id: "s5",
    category: "subah",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ",
    romanUrdu: "Allahumma anta rabbi la ilaha illa ant",
    urdu: "اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود نہیں",
    telugu: "ఓ అల్లాహ్! నువ్వే నా ప్రభువు, నీ తప్ప ఆరాధ్యుడు లేడు",
    source: "Bukhari",
  },
  {
    id: "s6",
    category: "subah",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    romanUrdu: "Subhanallahi wa bihamdih",
    urdu: "اللہ پاک ہے اور اس کی تعریف ہے",
    telugu: "అల్లాహ్ పవిత్రుడు, ప్రశంసలు ఆయనకే",
  },
  {
    id: "s7",
    category: "subah",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ",
    romanUrdu: "Allahumma inni as'alukal 'afiyah",
    urdu: "اے اللہ! میں تجھ سے عافیت مانگتا ہوں",
    telugu: "ఓ అల్లాహ్! నేను నిన్ను శాంతి అడుగుతున్నాను",
  },
  {
    id: "s8",
    category: "subah",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ",
    romanUrdu: "A'udhu bikalimatillahit tammati",
    urdu: "اللہ کے کامل کلمات کی پناہ مانگتا ہوں",
    telugu: "అల్లాహ్ యొక్క పరిపూర్ణ మాటల ఆశ్రయం కోరుతాను",
  },
  {
    id: "s9",
    category: "subah",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي",
    romanUrdu: "Allahumma 'afini fi badani",
    urdu: "اے اللہ! میرے جسم میں عافیت دے",
    telugu: "ఓ అల్లాహ్! నా శరీరానికి ఆరోగ్యం ప్రసాదించు",
    source: "Abu Dawud",
  },
  {
    id: "s10",
    category: "subah",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا",
    romanUrdu: "Raditu billahi rabban wa bil islami dinan",
    urdu: "میں اللہ کے رب ہونے اور اسلام کے دین ہونے پر راضی ہوں",
    telugu: "అల్లాహ్‌ను ప్రభువుగా, ఇస్లామ్‌ను ధర్మంగా అంగీకరించాను",
    source: "Tirmidhi",
  },

  // ── SHAAM (Evening) ──
  {
    id: "sh1",
    category: "shaam",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا",
    romanUrdu: "Allahumma bika amsayna wa bika asbahna",
    urdu: "اے اللہ! تیری توفیق سے شام ہوئی اور تیری توفیق سے صبح ہوئی",
    telugu: "ఓ అల్లాహ్! నీ సహాయంతో మేము సాయంత్రమయ్యాం",
  },
  {
    id: "sh2",
    category: "shaam",
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    romanUrdu: "A'udhu billahi minash shaitanir rajim",
    urdu: "میں شیطان مردود سے اللہ کی پناہ مانگتا ہوں",
    telugu: "శయతాన్ నుండి అల్లాహ్ శరణు కోరుతాను",
  },
  {
    id: "sh3",
    category: "shaam",
    arabic: "اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ",
    romanUrdu: "Allahumma ihfazni min bayni yadayya",
    urdu: "اے اللہ! میرے آگے سے میری حفاظت فرما",
    telugu: "ఓ అల్లాహ్! ముందు నుండి నన్ను కాపాడు",
  },
  {
    id: "sh4",
    category: "shaam",
    arabic: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ",
    romanUrdu: "Hasbiyallahu la ilaha illa hu",
    urdu: "مجھے اللہ کافی ہے، اس کے سوا کوئی معبود نہیں",
    telugu: "అల్లాహ్ నాకు చాలు, ఆయన తప్ప ఆరాధ్యుడు లేడు",
    source: "Abu Dawud",
  },
  {
    id: "sh5",
    category: "shaam",
    arabic: "اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ",
    romanUrdu: "Allahumma inni amsaytu ushiduk",
    urdu: "اے اللہ! میں شام کو تجھے گواہ بناتا ہوں",
    telugu: "ఓ అల్లాహ్! సాయంత్రం నిన్ను సాక్షిగా పెట్టాను",
  },
  {
    id: "sh6",
    category: "shaam",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    romanUrdu: "Bismillahir rahmanir raheem",
    urdu: "اللہ کے نام سے جو نہایت رحم کرنے والا ہے",
    telugu: "అల్లాహ్ పేరుతో, అతను అత్యంత దయామయుడు",
  },
  {
    id: "sh7",
    category: "shaam",
    arabic: "اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ",
    romanUrdu: "Allahumma ma amsa bi min ni'mah",
    urdu: "اے اللہ! شام کو جو نعمت مجھ پر ہے وہ تیری طرف سے ہے",
    telugu: "ఓ అల్లాహ్! ఈ సాయంత్రం నాకు ఉన్న అనుగ్రహం నీ నుండే",
  },
  {
    id: "sh8",
    category: "shaam",
    arabic: "اللَّهُمَّ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ",
    romanUrdu: "Allahumma fatiris samawati wal ard",
    urdu: "اے اللہ! آسمانوں اور زمین کے پیدا کرنے والے",
    telugu: "ఓ అల్లాహ్! ఆకాశాలు, భూమి సృష్టికర్తా",
    source: "Muslim",
  },
  {
    id: "sh9",
    category: "shaam",
    arabic: "أَعُوذُ بِعَفْوِكَ مِنْ عِقَابِكَ",
    romanUrdu: "A'udhu bi'afwika min 'iqabik",
    urdu: "میں تیری سزا سے تیری معافی کی پناہ مانگتا ہوں",
    telugu: "నీ శిక్ష నుండి నీ క్షమాపణలో ఆశ్రయం కోరుతాను",
  },
  {
    id: "sh10",
    category: "shaam",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ",
    romanUrdu: "Allahumma inni as'aluka khayra hazihil laylah",
    urdu: "اے اللہ! اس رات کی بھلائی مانگتا ہوں",
    telugu: "ఓ అల్లాహ్! ఈ రాత్రి మేలు అడుగుతున్నాను",
  },

  // ── NAMAZ KE BAAD (After Prayer) ──
  {
    id: "n1",
    category: "namaz",
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    romanUrdu: "Astaghfirullah (3 bar)",
    urdu: "میں اللہ سے معافی مانگتا ہوں (3 مرتبہ)",
    telugu: "అల్లాహ్ క్షమాపణ కోరుతాను (3 సార్లు)",
  },
  {
    id: "n2",
    category: "namaz",
    arabic: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ",
    romanUrdu: "Allahumma antas salam wa minkas salam",
    urdu: "اے اللہ! تو سلامتی ہے اور سلامتی تجھ سے ہے",
    telugu: "ఓ అల్లాహ్! నువ్వు సలామ్, సలామ్ నీ నుండే",
    source: "Muslim",
  },
  {
    id: "n3",
    category: "namaz",
    arabic: "سُبْحَانَ اللَّهِ (٣٣) الْحَمْدُ لِلَّهِ (٣٣) اللَّهُ أَكْبَرُ (٣٤)",
    romanUrdu: "Subhanallah 33x, Alhamdulillah 33x, Allahu Akbar 34x",
    urdu: "سبحان اللہ 33 بار، الحمد للہ 33 بار، اللہ اکبر 34 بار",
    telugu: "సుభానల్లాహ్ 33, అల్హమ్దులిల్లాహ్ 33, అల్లాహు అక్బర్ 34",
    source: "Bukhari",
  },
  {
    id: "n4",
    category: "namaz",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ",
    romanUrdu: "La ilaha illallahu wahdahu la sharika lahu, lahul mulku...",
    urdu: "اللہ کے سوا کوئی معبود نہیں، اکیلا ہے، بادشاہی اسی کی ہے",
    telugu: "అల్లాహ్ తప్ప ఆరాధ్యుడు లేడు, ఒంటరిగా, రాజ్యం ఆయనకే",
    source: "Muslim",
  },
  {
    id: "n5",
    category: "namaz",
    arabic: "اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ",
    romanUrdu: "Allahumma la mani'a lima a'tayt",
    urdu: "اے اللہ! جو تو دے اسے کوئی روکنے والا نہیں",
    telugu: "ఓ అల్లాహ్! నువ్వు ఇచ్చేది ఆపేవాడు లేడు",
    source: "Bukhari",
  },
  {
    id: "n6",
    category: "namaz",
    arabic: "آيَةُ الْكُرْسِيِّ — اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
    romanUrdu:
      "Ayatul Kursi (2:255) — Allahu la ilaha illa huwal hayyul qayyum",
    urdu: "آیت الکرسی — اللہ، اس کے سوا کوئی معبود نہیں، وہ زندہ جاوید قائم ہے",
    telugu: "ఆయతుల్ కుర్సీ — అల్లాహ్, ఆయన తప్ప ఆరాధ్యుడు లేడు",
    source: "Bukhari",
  },
  {
    id: "n7",
    category: "namaz",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ",
    romanUrdu: "Qul huwallahu ahad (3 bar)",
    urdu: "کہہ دو وہ اللہ ایک ہے (3 بار پڑھیں)",
    telugu: "చెప్పు: అల్లాహ్ ఒక్కడే (3 సార్లు చదవండి)",
  },
  {
    id: "n8",
    category: "namaz",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ",
    romanUrdu: "Allahumma a'inni 'ala dhikrika wa shukrik",
    urdu: "اے اللہ! تیرے ذکر اور شکر پر میری مدد فرما",
    telugu: "ఓ అల్లాహ్! నీ జ్ఞానం, కృతజ్ఞత పై నన్ను సహాయపడు",
    source: "Abu Dawud",
  },
  {
    id: "n9",
    category: "namaz",
    arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ",
    romanUrdu: "Rabbighfirli wa tub 'alayy",
    urdu: "اے رب! مجھے معاف کر اور توبہ قبول فرما",
    telugu: "ప్రభూ! నన్ను క్షమించి పశ్చాత్తాపం అంగీకరించు",
    source: "Tirmidhi",
  },
  {
    id: "n10",
    category: "namaz",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ",
    romanUrdu: "Allahumma salli 'ala Muhammad",
    urdu: "اے اللہ! حضرت محمد ﷺ پر درود بھیج",
    telugu: "ఓ అల్లాహ్! ముహమ్మద్ ﷺ పై దరూద్ పంపు",
  },

  // ── SAFAR (Travel) ──
  {
    id: "sf1",
    category: "safar",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا",
    romanUrdu: "Allahumma inna nas'aluka fi safarina",
    urdu: "اے اللہ! ہم اپنے سفر میں تجھ سے مانگتے ہیں",
    telugu: "ఓ అల్లాహ్! ఈ ప్రయాణంలో నిన్ను అడుగుతున్నాం",
  },
  {
    id: "sf2",
    category: "safar",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا",
    romanUrdu: "Subhana ladhi sakhkhara lana hadha",
    urdu: "پاک ہے وہ جس نے اسے ہمارے لیے مسخر کیا",
    telugu: "పవిత్రుడు అతను, దీన్ని మనకోసం అధీనపరిచాడు",
    source: "Quran 43:13",
  },
  {
    id: "sf3",
    category: "safar",
    arabic: "اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ",
    romanUrdu: "Allahumma antas sahibu fis safar",
    urdu: "اے اللہ! سفر میں تو ساتھی ہے",
    telugu: "ఓ అల్లాహ్! ప్రయాణంలో నువ్వే తోడు",
    source: "Muslim",
  },
  {
    id: "sf4",
    category: "safar",
    arabic: "رَبِّ أَنْزِلْنِي مُنْزَلًا مُبَارَكًا",
    romanUrdu: "Rabbi anzilni munzalan mubarakan",
    urdu: "اے رب! مجھے بابرکت منزل پر اتار",
    telugu: "ప్రభూ! బాగా బ్లెస్డ్ స్థానంలో నన్ను దింపు",
    source: "Quran 23:29",
  },
  {
    id: "sf5",
    category: "safar",
    arabic: "اللَّهُمَّ اطْوِ لَنَا الْأَرْضَ",
    romanUrdu: "Allahumma itwi lanal ard",
    urdu: "اے اللہ! ہمارے لیے زمین کو لپیٹ دے",
    telugu: "ఓ అల్లాహ్! మాకోసం భూమిని చుట్టు",
  },
  {
    id: "sf6",
    category: "safar",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ",
    romanUrdu: "Allahumma inni a'udhu bika min wa'tha'is safar",
    urdu: "اے اللہ! سفر کی تکلیف سے پناہ مانگتا ہوں",
    telugu: "ఓ అల్లాహ్! ప్రయాణ కష్టాల నుండి శరణు కోరుతాను",
    source: "Muslim",
  },
  {
    id: "sf7",
    category: "safar",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا",
    romanUrdu: "Allahumma barik lana fima razaqtana",
    urdu: "اے اللہ! جو رزق دیا اس میں برکت دے",
    telugu: "ఓ అల్లాహ్! ఇచ్చిన రిజ్కులో బరకత్ ఇవ్వు",
  },
  {
    id: "sf8",
    category: "safar",
    arabic: "اللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي",
    romanUrdu: "Allahumma aslih li dini",
    urdu: "اے اللہ! میرے دین کو درست فرما جو میرے معاملات کی حفاظت ہے",
    telugu: "ఓ అల్లాహ్! నా దీన్‌ను సరిచేయి",
  },

  // ── KHANA (Food) ──
  {
    id: "k1",
    category: "khana",
    arabic: "بِسْمِ اللَّهِ",
    romanUrdu: "Bismillah (khane se pehle)",
    urdu: "اللہ کے نام سے (کھانے سے پہلے پڑھیں)",
    telugu: "అల్లాహ్ పేరుతో (తినే ముందు చదవండి)",
    source: "Bukhari",
  },
  {
    id: "k2",
    category: "khana",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ",
    romanUrdu: "Allahumma barik lana fima razaqtana wa qina 'adhabin nar",
    urdu: "اے اللہ! جو رزق دیا اس میں برکت دے اور جہنم سے بچا",
    telugu: "ఓ అల్లాహ్! ఇచ్చిన రిజ్కులో బరకత్ ఇచ్చి నరకం నుండి కాపాడు",
  },
  {
    id: "k3",
    category: "khana",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا",
    romanUrdu: "Alhamdulillahil ladhi at'amani hadha",
    urdu: "اللہ کا شکر جس نے یہ کھانا دیا",
    telugu: "ఈ ఆహారం ఇచ్చిన అల్లాహ్‌కు కృతజ్ఞతలు",
    source: "Tirmidhi",
  },
  {
    id: "k4",
    category: "khana",
    arabic: "الْحَمْدُ لِلَّهِ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ",
    romanUrdu: "Alhamdulillahi hamdan kathiran tayyiban mubarakan fih",
    urdu: "اللہ کا بہت زیادہ، پاکیزہ اور بابرکت شکر",
    telugu: "అల్లాహ్‌కు చాలా, పవిత్రమైన, బ్లెస్డ్ కృతజ్ఞతలు",
    source: "Bukhari",
  },
  {
    id: "k5",
    category: "khana",
    arabic: "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي",
    romanUrdu: "Allahumma at'im man at'amani",
    urdu: "اے اللہ! جس نے مجھے کھلایا اسے بھی کھلا",
    telugu: "ఓ అల్లాహ్! నాకు తినిపించిన వారికి నువ్వూ తినిపించు",
    source: "Muslim",
  },
  {
    id: "k6",
    category: "khana",
    arabic: "اللَّهُمَّ اجْعَلْهُ رِزْقًا طَيِّبًا هَنِيئًا مَرِيئًا",
    romanUrdu: "Allahumma ij'alhu rizqan tayyiban hani'an mari'a",
    urdu: "اے اللہ! اسے پاکیزہ رزق بنا",
    telugu: "ఓ అల్లాహ్! దీన్ని పవిత్రమైన రిజ్కుగా చేయి",
  },
  {
    id: "k7",
    category: "khana",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا",
    romanUrdu: "Alhamdulillahil ladhi at'amana wa saqana",
    urdu: "اللہ کا شکر جس نے ہمیں کھلایا اور پلایا",
    telugu: "మాకు తిండి, నీళ్ళు ఇచ్చిన అల్లాహ్‌కు కృతజ్ఞతలు",
    source: "Tirmidhi",
  },

  // ── SONE SE PEHLE (Before Sleep) ──
  {
    id: "so1",
    category: "sone",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    romanUrdu: "Bismika Allahumma amutu wa ahya",
    urdu: "اے اللہ! تیرے نام سے مرتا اور جیتا ہوں",
    telugu: "ఓ అల్లాహ్! నీ పేరుతో మరణిస్తాను, జీవిస్తాను",
    source: "Bukhari",
  },
  {
    id: "so2",
    category: "sone",
    arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    romanUrdu: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak",
    urdu: "اے اللہ! جس دن تو بندوں کو اٹھائے گا عذاب سے بچا",
    telugu: "ఓ అల్లాహ్! నీ బందాలను లేపే రోజు శిక్ష నుండి కాపాడు",
    source: "Abu Dawud",
  },
  {
    id: "so3",
    category: "sone",
    arabic: "سُبْحَانَ اللَّهِ (٣٣) الْحَمْدُ لِلَّهِ (٣٣) اللَّهُ أَكْبَرُ (٣٤)",
    romanUrdu: "Subhanallah 33x, Alhamdulillah 33x, Allahu Akbar 34x",
    urdu: "تسبیح 33، تحمید 33، تکبیر 34 — سونے سے پہلے",
    telugu: "తస్బీహ్ 33, తహ్మీద్ 33, తక్బీర్ 34 — నిద్రకు ముందు",
    source: "Bukhari",
  },
  {
    id: "so4",
    category: "sone",
    arabic: "آيَةُ الْكُرْسِيِّ — اللَّهُ لَا إِلَهَ إِلَّا هُوَ",
    romanUrdu: "Ayatul Kursi (2:255) — sone se pehle",
    urdu: "آیت الکرسی پڑھ کر سوئیں — حضرت محمد ﷺ نے فرمایا",
    telugu: "నిద్రపోయే ముందు ఆయతుల్ కుర్సీ చదవండి",
    source: "Bukhari",
  },
  {
    id: "so5",
    category: "sone",
    arabic: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ",
    romanUrdu: "Allahumma aslamtu nafsi ilayk",
    urdu: "اے اللہ! میں نے اپنے آپ کو تیرے سپرد کیا",
    telugu: "ఓ అల్లాహ్! నన్ను నీకే అప్పగించాను",
    source: "Bukhari",
  },
  {
    id: "so6",
    category: "sone",
    arabic: "رَبِّ قِنِي عَذَابَكَ",
    romanUrdu: "Rabbi qini 'adhabak",
    urdu: "اے رب! مجھے اپنے عذاب سے بچا",
    telugu: "ప్రభూ! నీ శిక్ష నుండి నన్ను కాపాడు",
  },
  {
    id: "so7",
    category: "sone",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ",
    romanUrdu: "Allahumma inni as'alukal jannah",
    urdu: "اے اللہ! میں تجھ سے جنت مانگتا ہوں",
    telugu: "ఓ అల్లాహ్! నేను నిన్ను జన్నత్ అడుగుతున్నాను",
  },
  {
    id: "so8",
    category: "sone",
    arabic: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    romanUrdu: "Tabarak allazi biyadihil mulku — Surah Mulk padhen",
    urdu: "بابرکت ہے وہ جس کے ہاتھ میں بادشاہت ہے — سورہ ملک پڑھیں",
    telugu: "పరిపూర్ణుడు అతను, రాజ్యం ఆయన చేతిలో — సూరహ్ ముల్క్ చదవండి",
  },
];

export const CATEGORY_META: Record<
  string,
  { label: string; emoji: string; color: string }
> = {
  subah: { label: "Subah", emoji: "🌅", color: "#f59e0b" },
  shaam: { label: "Shaam", emoji: "🌇", color: "#ef4444" },
  namaz: { label: "Namaz ke Baad", emoji: "🕌", color: "#10b981" },
  safar: { label: "Safar", emoji: "✈️", color: "#3b82f6" },
  khana: { label: "Khana", emoji: "🍽️", color: "#8b5cf6" },
  sone: { label: "Sone se Pehle", emoji: "🌙", color: "#6366f1" },
};
